export {default as Navbar} from '../Navbar/Navbar'
export {default as Hero} from '../Hero/Hero'
export {default as NewProduct} from '../New Product/NewProduct'
export {default as BestSaler} from '../Best Saler/BestSaler'
export {default as ShowProduct} from '../ShowProduct/ShowProduct'
export {default as ProductCard} from '../Product/ProductCard'
export {default as Review} from '../Review/Review'
export {default as Footer} from '../Footer/Footer'
export {default as SingelProductCard} from '../SingelProduct/SingelProductCard'
export {default as Cart} from '../Cart/Cart'
export {default as Loader} from '../Loader/Loader'
export {default as Navigation} from '../navigation/Navigation'
export {default as AdressForm} from '../AdressForm/AdressForm'
export {default as PaymentForm} from '../Payment/PaymentForm'
export {default as Confirmation} from '../Confirmation/Confirmation'
export {default as LoginForm} from '../Form/LoginForm'
export {default as PrivateRoute} from '../Route/PrivateRoute'

